[package]
name = "passpot_crypto"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
aes-gcm = "0.10.3"
rand = "0.8.5"
base64 = "0.21.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
